# NOTE: there are alias suffixes configured for different backends:
#
# _all         all backends
# _unsafe    all backends, unsafe
#
# _no_std      all no_std backends
# _alloc       all alloc backends
#
# _ct          crossterm
# _nc          notcurses
# _sdl         sdl2
#
[alias]

# CHECK
cl = "clippy"
#
# backends:
cl_all = "clippy --features=all_std"
cl_ct = "clippy --features=crossterm"
cl_nc = "clippy --features=notcurses"
cl_sdl = "clippy --features=sdl2"
# unsafe:
cl_unsafe = "clippy --no-default-features --features=all_std,depura"
cl_no_std = "clippy --profile no_std --no-default-features --features=all_all_no_std,depura"
cl_alloc = "clippy --profile no_std --no-default-features --features=all_alloc,depura"

# CLEAN PACKAGE
cp = "clean --package"
crp = "clean --release --package"

# DOC
d = "doc --no-deps"
do = "doc --no-deps --open"
dd = "doc"
ddo = "doc --open"
#
d_all = "doc --no-deps --features=all_std"
do_all = "doc --no-deps --open --features=all_std"
dd_all = "doc --features=all_std"
ddo_all = "doc --open --features=all_std"
# +nightly; document everything
nd = "doc --no-deps --features=nightly,all_std"
ndo = "doc --no-deps --open --features=nightly,all_std"
ndd = "doc --features=nightly,all_std"
nddo = "doc --open --features=nightly,all_std"

# BUILD
b = "build"
bb = "build --bin"
be = "build --example"
br = "build --release"
brb = "build --release --bin"
bre = "build --release --example"
# crossterm
b_ct = "build --features=crossterm"
bb_ct = "build --features=crossterm --bin"
be_ct = "build --features=crossterm --example"
br_ct = "build --release --features=crossterm"
brb_ct = "build --release --features=crossterm --bin"
bre_ct = "build --release --features=crossterm --example"
# notcurses
b_nc = "build --features=notcurses"
bb_nc = "build --features=notcurses --bin"
be_nc = "build --features=notcurses --example"
br_nc = "build --release --features=notcurses"
brb_nc = "build --release --features=notcurses --bin"
bre_nc = "build --release --features=notcurses --example"
# sdl2
b_sdl = "build --features=sdl2"
bb_sdl = "build --features=sdl2 --bin"
be_sdl = "build --features=sdl2 --example"
br_sdl = "build --release --features=sdl2"
brb_sdl = "build --release --features=sdl2 --bin"
bre_sdl = "build --release --features=sdl2 --example"
# all
b_all = "build --features=all_std"
bb_all = "build --features=all_std --bin"
be_all = "build --features=all_std --example"
br_all = "build --release --features=all_std"
brb_all = "build --release --features=all_std --bin"
bre_all = "build --release --features=all_std --example"
# no_std | alloc
be_no_std = "build --profile no_std --no-default-features --features=all_no_std --example"
be_alloc = "build --profile no_std --no-default-features --features=all_alloc --example"
bre_no_std = "build --profile no_std-release --release --no-default-features --features=all_no_std --example"
bre_alloc = "build --profile no_std-release --release --no-default-features --features=all_alloc --example"


# RUN
r = "run"
rb = "run --bin"
re = "run --example"
rr = "run --release"
rrb = "run --release --bin"
rre = "run --release --example"
# crossterm
r_ct = "run --features=crossterm"
rr_ct = "run --release --features=crossterm"
rb_ct = "run --features=crossterm --bin"
re_ct = "run --features=crossterm --example"
rrb_ct = "run --release --features=crossterm --bin"
rre_ct = "run --release --features=crossterm --example"
# notcurses
r_nc = "run --features=notcurses"
rr_nc = "run --release --features=notcurses"
rb_nc = "run --features=notcurses --bin"
re_nc = "run --features=notcurses --example"
rrb_nc = "run --release --features=notcurses --bin"
rre_nc = "run --release --features=notcurses --example"
# sdl2
r_sdl = "run --features=sdl2"
rb_sdl = "run --features=sdl2 --bin"
re_sdl = "run --features=sdl2 --example"
rr_sdl = "run --release --features=sdl2"
rrb_sdl = "run --release --features=sdl2 --bin"
rre_sdl = "run --release --features=sdl2 --example"
# all
r_all = "run --features=all_std"
rr_all = "run --release --features=all_std"
rb_all = "run --features=all_std --bin"
re_all = "run --features=all_std --example"
rrb_all = "run --release --features=all_std --bin"
rre_all = "run --release --features=all_std --example"
# all_unsafe
r_all_unsafe = "run --no-default-features --features=all_std,depura"
rr_all_unsafe = "run --release --no-default-features --features=all_std,depura"
rb_all_unsafe = "run --no-default-features --features=all_std,depura --bin"
re_all_unsafe = "run --no-default-features --features=all_std,depura --example"
rrb_all_unsafe = "run --release --no-default-features --features=all_std,depura --bin"
rre_all_unsafe = "run --release --no-default-features --features=all_std,depura --example"
# no_std | alloc
re_no_std = "run --profile no_std --no-default-features --features=all_no_std --example"
re_alloc = "run --profile no_std --no-default-features --features=all_alloc --example"
rre_no_std = "run --profile no_std-release --release --no-default-features --features=all_no_std --example"
rre_alloc = "run --profile no_std-release --release --no-default-features --features=all_alloc --example"

# TEST
t = "test"
td = "test --doc"
t_ = "test -- --nocapture"
t_1 = "test -- --test-threads 1 --nocapture"
#
t_ct = "test --features=crossterm"
td_ct = "test --doc --features=crossterm"
#
t_nc = "test --features=notcurses"
td_nc = "test --doc --features=notcurses"
#
t_all = "test --features=all_std"
td_all = "test --doc --features=all_std"

# TREE
tr = "tree"
trf = "tree --format {p}:{f}" # with feature list
trr = "tree --format {p}:{r}" # with repository url
# crossterm
tr_ct = "tree --features=crossterm"
trf_ct = "tree --format {p}:{f} --features=crossterm"
trr_ct = "tree --format {p}:{r} --features=crossterm"
# notcurses
tr_nc = "tree --features=notcurses"
trf_nc = "tree --format {p}:{f} --features=notcurses"
trr_nc = "tree --format {p}:{r} --features=notcurses"
# sdl2
tr_sdl = "tree --features=sdl2"
trf_sdl = "tree --format {p}:{f} --features=sdl2"
trr_sdl = "tree --format {p}:{r} --features=sdl2"
# all
tr_all = "tree --features=all_std"
trf_all = "tree --format {p}:{f} --features=all_std"
trr_all = "tree --format {p}:{r} --features=all_std"

# PUBLISH
p = "publish --dry-run"
pa = "publish --dry-run --allow-dirty"
PUBLISH = "publish"
PUBLISHa = "publish --allow-dirty"

# Cargo subcommands:
## cargo-expand
E = "expand"
Eb = "expand --bin"
Ee = "expand --example"
El = "expand --lib"
# crossterm
E_ct = "expand  --features=crossterm"
Eb_ct = "expand --bin --features=crossterm"
Ee_ct = "expand --example --features=crossterm"
El_ct = "expand --lib --features=crossterm"
# notcurses
E_nc = "expand  --features=notcurses"
Eb_nc = "expand --bin --features=notcurses"
Ee_nc = "expand --example --features=notcurses"
El_nc = "expand --lib --features=notcurses"
# sdl2
E_sdl = "expand  --features=sdl2"
Eb_sdl = "expand --bin --features=sdl2"
Ee_sdl = "expand --example --features=sdl2"
El_sdl = "expand --lib --features=sdl2"
# all
E_all = "expand  --features=all_std"
Eb_all = "expand --bin --features=all_std"
Ee_all = "expand --example --features=all_std"
El_all = "expand --lib --features=all_std"

[build]
