# NOTE: there are alias suffixes configured for different backends:
#
# _all         all backends
# _unsafe    all backends, unsafe
#
# _no_std      all no_std backends
# _alloc       all alloc backends
#
# _ct          crossterm
# _nc          notcurses
# _sdl         sdl2
#
[alias]

# CHECK
cl = "clippy"
#
# backends:
cl_all = "clippy -F dep_std"
cl_ct = "clippy -F crossterm"
cl_nc = "clippy -F notcurses"
cl_sdl = "clippy -F sdl2"
# unsafe:
cl_unsafe = "clippy --no-default-features -F dep_std"
cl_no_std = "clippy --profile no_std --no-default-features -F dep_dep_no_std"
cl_alloc = "clippy --profile no_std --no-default-features -F dep_alloc"

# CLEAN PACKAGE
cp = "clean --package"
crp = "clean --release --package"

# DOC
d = "doc --no-deps"
do = "doc --no-deps --open"
dd = "doc"
ddo = "doc --open"
#
d_all = "doc --no-deps -F dep_std"
do_all = "doc --no-deps --open -F dep_std"
dd_all = "doc -F dep_std"
ddo_all = "doc --open -F dep_std"
# +nightly; document everything
nd = "doc --no-deps -F nightly,dep_std"
ndo = "doc --no-deps --open -F nightly,dep_std"
ndd = "doc -F nightly,dep_std"
nddo = "doc --open -F nightly,dep_std"

# BUILD
b = "build"
bb = "build --bin"
be = "build --example"
br = "build --release"
brb = "build --release --bin"
bre = "build --release --example"
# crossterm
b_ct = "build -F crossterm"
bb_ct = "build -F crossterm --bin"
be_ct = "build -F crossterm --example"
br_ct = "build --release -F crossterm"
brb_ct = "build --release -F crossterm --bin"
bre_ct = "build --release -F crossterm --example"
# notcurses
b_nc = "build -F notcurses"
bb_nc = "build -F notcurses --bin"
be_nc = "build -F notcurses --example"
br_nc = "build --release -F notcurses"
brb_nc = "build --release -F notcurses --bin"
bre_nc = "build --release -F notcurses --example"
# sdl2
b_sdl = "build -F sdl2"
bb_sdl = "build -F sdl2 --bin"
be_sdl = "build -F sdl2 --example"
br_sdl = "build --release -F sdl2"
brb_sdl = "build --release -F sdl2 --bin"
bre_sdl = "build --release -F sdl2 --example"
# all
b_all = "build -F dep_std"
bb_all = "build -F dep_std --bin"
be_all = "build -F dep_std --example"
br_all = "build --release -F dep_std"
brb_all = "build --release -F dep_std --bin"
bre_all = "build --release -F dep_std --example"
# no_std | alloc
be_no_std = "build --profile no_std --no-default-features -F dep_no_std,unsafe_libc --example"
be_alloc = "build --profile no_std --no-default-features -F dep_alloc,unsafe_libc --example"
bre_no_std = "build --profile no_std-release --release --no-default-features -F dep_no_std,unsafe_libc --example"
bre_alloc = "build --profile no_std-release --release --no-default-features -F dep_alloc,unsafe_libc --example"


# RUN
r = "run"
rb = "run --bin"
re = "run --example"
rr = "run --release"
rrb = "run --release --bin"
rre = "run --release --example"
# crossterm
r_ct = "run -F crossterm"
rr_ct = "run --release -F crossterm"
rb_ct = "run -F crossterm --bin"
re_ct = "run -F crossterm --example"
rrb_ct = "run --release -F crossterm --bin"
rre_ct = "run --release -F crossterm --example"
# notcurses
r_nc = "run -F notcurses"
rr_nc = "run --release -F notcurses"
rb_nc = "run -F notcurses --bin"
re_nc = "run -F notcurses --example"
rrb_nc = "run --release -F notcurses --bin"
rre_nc = "run --release -F notcurses --example"
# sdl2
r_sdl = "run -F sdl2"
rb_sdl = "run -F sdl2 --bin"
re_sdl = "run -F sdl2 --example"
rr_sdl = "run --release -F sdl2"
rrb_sdl = "run --release -F sdl2 --bin"
rre_sdl = "run --release -F sdl2 --example"
# all
r_all = "run -F dep_std"
rr_all = "run --release -F dep_std"
rb_all = "run -F dep_std --bin"
re_all = "run -F dep_std --example"
rrb_all = "run --release -F dep_std --bin"
rre_all = "run --release -F dep_std --example"
# dep_unsafe
r_dep_unsafe = "run --no-default-features -F dep_std"
rr_dep_unsafe = "run --release --no-default-features -F dep_std"
rb_dep_unsafe = "run --no-default-features -F dep_std --bin"
re_dep_unsafe = "run --no-default-features -F dep_std --example"
rrb_dep_unsafe = "run --release --no-default-features -F dep_std --bin"
rre_dep_unsafe = "run --release --no-default-features -F dep_std --example"
# no_std | alloc
re_no_std = "run --profile no_std --no-default-features -F dep_no_std --example"
re_alloc = "run --profile no_std --no-default-features -F dep_alloc --example"
rre_no_std = "run --profile no_std-release --release --no-default-features -F dep_no_std --example"
rre_alloc = "run --profile no_std-release --release --no-default-features -F dep_alloc --example"

# TEST
t = "test"
td = "test --doc"
t_ = "test -- --nocapture"
t_1 = "test -- --test-threads 1 --nocapture"
#
t_ct = "test -F crossterm"
td_ct = "test --doc -F crossterm"
#
t_nc = "test -F notcurses"
td_nc = "test --doc -F notcurses"
#
t_all = "test -F dep_std"
td_all = "test --doc -F dep_std"

# TREE
tr = "tree"
trf = "tree --format {p}:{f}" # with feature list
trr = "tree --format {p}:{r}" # with repository url
# crossterm
tr_ct = "tree -F crossterm"
trf_ct = "tree --format {p}:{f} -F crossterm"
trr_ct = "tree --format {p}:{r} -F crossterm"
# notcurses
tr_nc = "tree -F notcurses"
trf_nc = "tree --format {p}:{f} -F notcurses"
trr_nc = "tree --format {p}:{r} -F notcurses"
# sdl2
tr_sdl = "tree -F sdl2"
trf_sdl = "tree --format {p}:{f} -F sdl2"
trr_sdl = "tree --format {p}:{r} -F sdl2"
# all
tr_all = "tree -F dep_std"
trf_all = "tree --format {p}:{f} -F dep_std"
trr_all = "tree --format {p}:{r} -F dep_std"

# PUBLISH
p = "publish --dry-run"
pa = "publish --dry-run --allow-dirty"
PUBLISH = "publish"
PUBLISHa = "publish --allow-dirty"

# Cargo subcommands:
## cargo-expand
E = "expand"
Eb = "expand --bin"
Ee = "expand --example"
El = "expand --lib"
# crossterm
E_ct = "expand  -F crossterm"
Eb_ct = "expand --bin -F crossterm"
Ee_ct = "expand --example -F crossterm"
El_ct = "expand --lib -F crossterm"
# notcurses
E_nc = "expand  -F notcurses"
Eb_nc = "expand --bin -F notcurses"
Ee_nc = "expand --example -F notcurses"
El_nc = "expand --lib -F notcurses"
# sdl2
E_sdl = "expand  -F sdl2"
Eb_sdl = "expand --bin -F sdl2"
Ee_sdl = "expand --example -F sdl2"
El_sdl = "expand --lib -F sdl2"
# all
E_all = "expand  -F dep_std"
Eb_all = "expand --bin -F dep_std"
Ee_all = "expand --example -F dep_std"
El_all = "expand --lib -F dep_std"

[build]
