# NOTE: there are alias suffixes configured for different backends:
#
# _all         all backends
# _all_nostd   all no-std backends
#
# _ct          crossterm
# _nc          notcurses
#
[alias]

# CHECK
cl = "clippy"
#
# backends
cl_all = "clippy --features=all_backends"
cl_ct = "clippy --features=crossterm"
cl_nc = "clippy --features=notcurses"
# cl_no-std = "clippy --no-default-features --features=all_no-std_backends"
# cl_alloc = "clippy --profile alloc --no-default-features --features=all_alloc_backends"

# CLEAN PACKAGE
cp = "clean --package"
crp = "clean --release --package"

# DOC
d = "doc --no-deps"
do = "doc --no-deps --open"
dd = "doc"
ddo = "doc --open"
#
d_all = "doc --no-deps --features=all_backends"
do_all = "doc --no-deps --open --features=all_backends"
dd_all = "doc --features=all_backends"
ddo_all = "doc --open --features=all_backends"
# nightly:
nd = "doc --no-deps --features=nightly"
ndo = "doc --no-deps --open --features=nightly"
nd_all = "doc --no-deps --features=all_backends,nightly"
ndo_all = "doc --no-deps --open --features=all_backends,nightly"
ndd_all = "doc --features=all_backends,nightly"
nddo_all = "doc --open --features=all_backends,nightly"

# BUILD
b = "build"
bb = "build --bin"
be = "build --example"
br = "build --release"
brb = "build --release --bin"
bre = "build --release --example"
#
b_ct = "build --features=crossterm"
bb_ct = "build --features=crossterm --bin"
be_ct = "build --features=crossterm --example"
br_ct = "build --release --features=crossterm"
brb_ct = "build --release --features=crossterm --bin"
bre_ct = "build --release --features=crossterm --example"
#
b_nc = "build --features=notcurses"
bb_nc = "build --features=notcurses --bin"
be_nc = "build --features=notcurses --example"
br_nc = "build --release --features=notcurses"
brb_nc = "build --release --features=notcurses --bin"
bre_nc = "build --release --features=notcurses --example"
#
b_all = "build --features=all_backends"
bb_all = "build --features=all_backends --bin"
be_all = "build --features=all_backends --example"
br_all = "build --release --features=all_backends"
brb_all = "build --release --features=all_backends --bin"
bre_all = "build --release --features=all_backends --example"

# RUN
r = "run"
rb = "run --bin"
re = "run --example"
rr = "run --release"
rrb = "run --release --bin"
rre = "run --release --example"
# crossterm
r_ct = "run --features=crossterm"
rr_ct = "run --release --features=crossterm"
rb_ct = "run --features=crossterm --bin"
re_ct = "run --features=crossterm --example"
rrb_ct = "run --release --features=crossterm --bin"
rre_ct = "run --release --features=crossterm --example"
# notcurses
r_nc = "run --features=notcurses"
rr_nc = "run --release --features=notcurses"
rb_nc = "run --features=notcurses --bin"
re_nc = "run --features=notcurses --example"
rrb_nc = "run --release --features=notcurses --bin"
rre_nc = "run --release --features=notcurses --example"
# all
r_all = "run --features=all_backends"
rr_all = "run --release --features=all_backends"
rb_all = "run --features=all_backends --bin"
re_all = "run --features=all_backends --example"
rrb_all = "run --release --features=all_backends --bin"
rre_all = "run --release --features=all_backends --example"
# no-std | alloc
# re_no-std = "run --no-default-features --features=all_no-std_backends --example"
# rre_no-std = "run --release --no-default-features --features=all_no-std_backends --example"
# re_alloc = "run --profile alloc --no-default-features --features=all_alloc_backends --example"
# rre_alloc = "run --profile alloc --release --no-default-features --features=all_alloc_backends --example"

# TEST
t = "test"
td = "test --doc"
t_ = "test -- --nocapture"
t_1 = "test -- --test-threads 1 --nocapture"
#
t_ct = "test --features=crossterm"
td_ct = "test --doc --features=crossterm"
#
t_nc = "test --features=notcurses"
td_nc = "test --doc --features=notcurses"
#
t_all = "test --features=all_backends"
td_all = "test --doc --features=all_backends"

# TREE
tr = "tree"
trf = "tree --format {p}:{f}" # with feature list
trr = "tree --format {p}:{r}" # with repository url
#
tr_ct = "tree --features=crossterm"
trf_ct = "tree --format {p}:{f} --features=crossterm"
trr_ct = "tree --format {p}:{r} --features=crossterm"
#
tr_nc = "tree --features=notcurses"
trf_nc = "tree --format {p}:{f} --features=notcurses"
trr_nc = "tree --format {p}:{r} --features=notcurses"
#
tr_all = "tree --features=all_backends"
trf_all = "tree --format {p}:{f} --features=all_backends"
trr_all = "tree --format {p}:{r} --features=all_backends"

# PUBLISH
p = "publish --dry-run"
pa = "publish --dry-run --allow-dirty"
pp = "publish"
ppa = "publish --allow-dirty"

# Cargo subcommands:
## cargo-expand
E = "expand"
Eb = "expand --bin"
Ee = "expand --example"
El = "expand --lib"
#
E_ct = "expand  --features=crossterm"
Eb_ct = "expand --bin --features=crossterm"
Ee_ct = "expand --example --features=crossterm"
El_ct = "expand --lib --features=crossterm"
#
E_nc = "expand  --features=notcurses"
Eb_nc = "expand --bin --features=notcurses"
Ee_nc = "expand --example --features=notcurses"
El_nc = "expand --lib --features=notcurses"
#
E_all = "expand  --features=all_backends"
Eb_all = "expand --bin --features=all_backends"
Ee_all = "expand --example --features=all_backends"
El_all = "expand --lib --features=all_backends"

[build]
